name = "cloudsim"
version = "1.0.0"
license = "license"
author = "Diego E. Oleiaz"
maintainer = "diegooleiarz@hotmail.com"
copyright = "Copyright 2024, Diego E. Oleiaz"

[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[[executable]]
name = "model"
source-dir = "app"
main = "main.f90"

[fortran]
implicit-typing = true
implicit-external = true
source-form = "default"

# implicit-typing = false
# implicit-external = false
# source-form = "free"

[dependencies]
forbear = {git="https://github.com/szaghi/forbear"}