[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=40.8.0", 
             "fpm", 
             "numpy==1.26.4",
             "wheel", 
             "matplotlib",
             "scipy", 
             "pandas"]

