name: Continuous Integration
on:
  push:
    branches: [ "initials" ]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Install Python
        uses: actions/setup-python@v5 # Use pip to install latest CMake, & FORD/Jin2For, etc.
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel
            
      - uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.2

      - name: Build wheels
        run: python -m cibuildwheel python/ --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/wheelhouse/


  deploy:
    needs: [build_wheels]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/wheelhouse/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        pip install twine
        twine upload --repository testpypi wheelhouse/*