name: Continuous Integration
on:
  push:
    branches: [ "CI" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [12, 13] # Version of GFortran we want to use.
        python-version: ['3.10', '3.11', '3.12']
    env:
      FC: gfortran-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Setup Fortran Compiler
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: gcc
        version: ${{ matrix.gcc_v }}

    - name: Install Python
      uses: actions/setup-python@v5 # Use pip to install latest CMake, & FORD/Jin2For, etc.
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2
    - name: Setup Fortran Package Manager
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Python dependencies
      if: contains( matrix.os, 'ubuntu')
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        pip install wheel ford numpy matplotlib numpy scipy meson ninja
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install meson
      working-directory: ./python
      run: |
        sudo apt-get install libnlopt-dev meson
        pip install meson tox

    - name: Compile
      working-directory: python
      run: fpm build --profile release

    - name: Install cloudmodel
      working-directory: python
      run:
        pip install .

  build_wheels:
    needs: [build]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Install Python
        uses: actions/setup-python@v5 # Use pip to install latest CMake, & FORD/Jin2For, etc.
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel
            
      - uses: actions/checkout@v4

      - name: Build wheels
        working-directory: python
        run: python -m cibuildwheel --output-dir wheelhouse
      
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/wheelhouse/


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        working-directory: python
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: python/dist/*.tar.gz

  deploy:
    needs: [build_wheels, build_sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
          path: ./python/wheelhouse/
          pattern: cibw-*
          merge-multiple: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Twine dependencies
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      working-directory: python
      run: 
        twine upload --repository testpypi wheelhouse/*
