name: Continuous Integration
on:
  push:
    branches: [ "fortran_comp" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [13] # Version of GFortran we want to use.
        python-version: ['3.10', '3.11']
    env:
      FC: gfortran-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Setup Fortran Compiler
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: gcc
        version: ${{ matrix.gcc_v }}
    - name: Install Python
      uses: actions/setup-python@v5 # Use pip to install latest CMake, & FORD/Jin2For, etc.
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2
    - name: Setup Fortran Package Manager
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Python dependencies
      if: contains( matrix.os, 'ubuntu')
      run: |
        python -m pip install --upgrade pip
        pip install wheel ford numpy matplotlib numpy scipy meson ninja
        if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi

    - name: Install GFortran Linux
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo apt-get install lcov
        sudo update-alternatives \
           --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc_v }} 100 \
           --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.gcc_v }} \
           --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.gcc_v }}

    - name: Install meson
      working-directory: ./python
      run: |
        sudo apt-get install libnlopt-dev meson
        pip install meson tox

    - name: Compile
      working-directory: python
      run: fpm build --profile release
      
    - name: Compile
      working-directory: .
      run: ls build -a

    - name: Install cloudmodel
      working-directory: python
      run:
        pip install .
    
  build-manylinux:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cibuildwheel
        run: pip wheel -w dist ./python/ --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: [build, build-manylinux]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USER }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
      run: |
        python -m pip install --upgrade pip
        pip install twine
        ls dist
        twine upload --repository testpypi dist/*